version: 1.0.{build}
os: Visual Studio 2015
build: off 

environment:
  JSPM_GITHUB_AUTH_TOKEN:
    secure: 64Ur2veyh/2KC6BjqgVZKlPx5cj5RgZQkw7lyeKBzyJmLb8sucaixeuKrY4psz+7
    
install:
#- ps: Install-product node 6.2.0
- node --version
- npm install jspm@0.16.54 -g --depth 0
- npm install --depth 0
- jspm config registries.github.auth %JSPM_GITHUB_AUTH_TOKEN%
- jspm install -y
